<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pb8HGoXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pb8HGoX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pb8HGoX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'versioningService' => ['privates', 'App\\Service\\VersioningService', 'getVersioningServiceService', true],
        ], [
            'bookRepository' => 'App\\Repository\\BookRepository',
            'cache' => '?',
            'serializer' => '?',
            'versioningService' => 'App\\Service\\VersioningService',
        ]);
    }
}
