<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N3UvHoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N3Uv_ho' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N3Uv_ho'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authorRepository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'currentBook' => ['privates', '.errored..service_locator.N3Uv_ho.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.N3Uv_ho": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'authorRepository' => 'App\\Repository\\AuthorRepository',
            'cache' => '?',
            'currentBook' => 'App\\Entity\\Book',
            'em' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
