<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VuDI7p1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vuDI7p1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vuDI7p1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cachePool' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'cachePool' => '?',
            'em' => '?',
            'serializer' => '?',
            'urlGenerator' => '?',
            'validator' => '?',
        ]);
    }
}
