<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQgCrOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u_qgCrO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u_qgCrO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'author' => ['privates', '.errored..service_locator.u_qgCrO.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.u_qgCrO": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".'],
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'cachePool' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'author' => 'App\\Entity\\Author',
            'bookRepository' => 'App\\Repository\\BookRepository',
            'cachePool' => '?',
            'em' => '?',
        ]);
    }
}
