<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z7WDD7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z7WDD7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z7WDD7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.Z7WDD7F.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.Z7WDD7F": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'versioningService' => ['privates', 'App\\Service\\VersioningService', 'getVersioningServiceService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'serializer' => '?',
            'versioningService' => 'App\\Service\\VersioningService',
        ]);
    }
}
