<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_25DNpNmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.25DNpNm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.25DNpNm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.25DNpNm.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.25DNpNm": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'cachePool' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'cachePool' => '?',
            'em' => '?',
        ]);
    }
}
