<?php

namespace ContainerTEMVVqU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthor3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zwFgvKV.App\Entity\Author' shared service.
     *
     * @return \App\Entity\Author
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zwFgvKV": it needs an instance of "App\\Entity\\Author" but this type has been excluded in "config/services.yaml".');
    }
}
