<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTEMVVqU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTEMVVqU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTEMVVqU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTEMVVqU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTEMVVqU\App_KernelDevDebugContainer([
    'container.build_hash' => 'TEMVVqU',
    'container.build_id' => 'd4f5373e',
    'container.build_time' => 1719488570,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTEMVVqU');
